name: Reusable - Dockerfile Lint (Hadolint)

on:
  workflow_call:
    inputs:
      artifact-suffix:
        required: true
        type: string
      retention-days:
        required: false
        type: number
        default: 7

jobs:
  hadolint:
    name: Dockerfile Lint (Hadolint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Run Hadolint on Backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile
          output-file: hadolint-backend.txt
          no-fail: true

      - name: Run Hadolint on Frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: frontend/Dockerfile
          output-file: hadolint-frontend.txt
          no-fail: true

      - name: Upload Hadolint Reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: hadolint-report-${{ inputs.artifact-suffix }}
          path: |
            hadolint-backend.txt
            hadolint-frontend.txt
          retention-days: ${{ inputs.retention-days }}
