name: Reusable - Secret Scan

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  gitleaks:
    name: Secret Scan (Gitleaks)
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
