name: Reusable - Trivy Filesystem Scan

on:
  workflow_call:
    inputs:
      artifact-suffix:
        required: true
        type: string
      exit-code:
        required: false
        type: number
        default: 0
      retention-days:
        required: false
        type: number
        default: 7

jobs:
  trivy-fs:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          exit-code: ${{ inputs.exit-code }}
          output: trivy-fs-results.txt

      - name: Upload Trivy FS report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: trivy-fs-report-${{ inputs.artifact-suffix }}
          path: trivy-fs-results.txt
          retention-days: ${{ inputs.retention-days }}
