name: Staging pipeline

on:
  push:
    branches: [qa]

jobs:
  # SECRET SCANNING
  gitleaks:
    name: Secret Scan (Gitleaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # SAST AND DEPENDENCY SECURITY
  sast:
    name: SAST (Bandit)
    runs-on: ubuntu-latest
    needs: gitleaks

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r backend -f json -o bandit-report.json --severity-level medium --confidence-level medium

      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: bandit-report-staging
          path: bandit-report.json
          retention-days: 14

  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    needs: gitleaks

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: pip audit
        run: |
          pip install pip-audit
          pip-audit -r backend/requirements.txt --format json --output pip-audit.json

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: npm audit
        working-directory: frontend
        run: |
          npm install
          npm audit --audit-level high --json > npm-audit.json

      - name: Upload dependency reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: dependency-report-staging
          path: |
            pip-audit.json
            frontend/npm-audit.json
          retention-days: 14

  trivy-fs:
    name: Trivy filesystem Scan
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1
          output: trivy-fs-results.txt

      - name: Upload Trivy FS report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: trivy-fs-report-staging
          path: trivy-fs-results.txt
          retention-days: 14

  hadolint:
    name: Dockerfile Lint (Hadolint)
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Run Hadolint on Backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile
          output-file: hadolint-backend.txt
          no-fail: true

      - name: Run Hadolint on Frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: frontend/Dockerfile
          output-file: hadolint-frontend.txt
          no-fail: true

      - name: Upload Hadolint Reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: hadolint-report-staging
          path: |
            hadolint-backend.txt
            hadolint-frontend.txt
          retention-days: 14

  build:
    name: Build Docker Images and push to Docker Hub
    runs-on: ubuntu-latest
    environment: staging
    needs:
      - sast
      - dependency-scan
      - trivy-fs
      - hadolint
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      backend_digest: ${{ steps.build-backend.outputs.digest }}
      frontend_digest: ${{ steps.build-frontend.outputs.digest }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Generate Image Tag
        id: version
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=staging-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Backend Image
        id: build-backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ steps.version.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_IMAGE }}:latest-staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Frontend Image
        id: build-frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.FRONTEND_IMAGE }}:${{ steps.version.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.FRONTEND_IMAGE }}:latest-staging
          cache-from: type=gha
          cache-to: type=gha,mode=max
